language: php
php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install
 
script:
  - vendor/bin/phpunit --testdox --coverage-html coverage --coverage-clover clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
